# Generated by Django 4.2.8 on 2023-12-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airplanes', '0002_alter_airplane_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplane',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='airplane',
            name='passenger_assumptions',
            field=models.PositiveIntegerField(),
        ),
    ]
